modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "unchained"
version = "1.6-neoforge-1.2.0"
displayName = "Cobblemon Unchained"
authors = "timinc aka Timothy Metcalfe"
description = '''
Chain KOs and captures to boost spawns around you.
'''

[[dependencies.unchained]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.unchained]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unchained]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,1.7.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.unchained]]
modId = "cobbled_counter"
mandatory = true
versionRange = "[1.6-neoforge-1.5.0,)"
ordering = "AFTER"
side = "BOTH"
